apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-nodeport
spec:
  containers:
  - name: nginx-np
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80