apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
spec:
  containers:
  - name: nginx-lb
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80