apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: nginx
      ports:
        - containerPort: 90
      envFrom:
        - secretRef:
            name: devops-secret