apiVersion: v1
kind: Secret
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    ports:
    - containerPort:80
    envFrom:
    - secretRef:
      name: devops-secret